version: 2
jobs:
  job1:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test
  job2:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: cat sum.js
workflows:
  version: 2
  one-and-two:
    jobs:
      - job1
      - job2
